### ISSUE TITLE
[bug] Gender gets synced

### ISSUE THREAD

**Issue by FlipperLP** [antonplagemann/GoogleMonicaSync#62]
Hello! I just quickly wanted to let you know that google doesn't have a gender field, and unfortunately that gets synced to monica, making it impossible to set. Much Love, Phil

**Comment by antonplagemann** [comment]
Hi Phil,

thanks a lot for your report! The issue should be fixed in v.5.0.1 😊 
Let me know if you are still experiencing the issue or if there are other thoughts to share.
